### ISSUE TITLE
[Docs] Invalid Links for Use Guide PPT and PDF in README.md

### ISSUE THREAD

**Issue by powerkimhub** [m-cmp/mc-observability#14]
- 대상 파일을 찾긴 했는데, 
- 링크 깨짐은 확인해보시는 것이 좋을 것 같습니다.
- 궁극적으로는 ppt/pdf 파일 내용도 오픈 협업 작업이 가능할 수 있도록 markdown 형식으로 전환하시는 것을 좋을 듯합니다. 
- 참고: 대상 링크 위치

<p align="left">
<img width=400 src="https://github.com/m-cmp/mc-observability/assets/46367962/7e52124b-19c6-4db1-ad02-c1b43faec2f1">
<br>
</p>

**Comment by hyeon-inno** [comment]
피드백 감사합니다.
해당 내용은 markdown 형식으로 전환을 조속히 진행하여 링크 깨짐 현상과 더불어 빠르게 해결될 수 있도록 하겠습니다.

**Comment by hyeon-inno** [comment]
[대상 내용 변경 완료되었습니다.](https://github.com/m-cmp/mc-observability/pull/16)
